config/routes.rb
SecondTrial::Application.routes.draw do
    
  resources :problem_categories

  resources :categories

  resources :problem_in_contests

  resources :participants

  resources :contests

  resources :problems do
      resources :submissions
  end

    devise_for :users
    match 'users/:id' => 'users#show', :via => [:get]
    match '/about' => 'welcome#about', :via => [:get]
  get "welcome/index"
  

  root 'welcome#index'

  

end

app/models/problem_category.rb
class ProblemCategory < ActiveRecord::Base
	belongs_to :category
	belongs_to :problem
	
end

app/controllers/problem_categories_controller.rb
class ProblemCategoriesController < ApplicationController
  before_action :set_problem_category, only: [:show, :edit, :update, :destroy]

  # GET /problem_categories
  # GET /problem_categories.json
  def index
    @problem_categories = ProblemCategory.all
  end

  # GET /problem_categories/1
  # GET /problem_categories/1.json
  def show
  end

  # GET /problem_categories/new
  def new
    @problem_category = ProblemCategory.new
  end

  # GET /problem_categories/1/edit
  def edit
  end

  # POST /problem_categories
  # POST /problem_categories.json
  def create
    @problem_category = ProblemCategory.new(problem_category_params)

    respond_to do |format|
      if @problem_category.save
        format.html { redirect_to @problem_category, notice: 'Problem category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @problem_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @problem_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problem_categories/1
  # PATCH/PUT /problem_categories/1.json
  def update
    respond_to do |format|
      if @problem_category.update(problem_category_params)
        format.html { redirect_to @problem_category, notice: 'Problem category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @problem_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problem_categories/1
  # DELETE /problem_categories/1.json
  def destroy
    @problem_category.destroy
    respond_to do |format|
      format.html { redirect_to problem_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem_category
      @problem_category = ProblemCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_category_params
      params.require(:problem_category).permit(:problem_id, :category_id)
    end
end

app/helpers/problem_categories_helper.rb
module ProblemCategoriesHelper
end

app/views/problem_categories/_form.html.erb
<%= simple_form_for(@problem_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :problem, value_method: :id, :as => :hidden, :input_html => {:value =>(@problem.id) }, include_blank: false %>    
    <%= f.association :category , label_method: :category , value_method: :id , include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/problem_categories/edit.html.erb
<h1>Editing problem_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem_category %> |
<%= link_to 'Back', problem_categories_path %>

app/views/problem_categories/index.html.erb
<h1>Listing problem_categories</h1>

<table>
  <thead>
    <tr>
      <th>Problem</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @problem_categories.each do |problem_category| %>
      <tr>
        <td><%= problem_category.problem_id %></td>
        <td><%= problem_category.category_id %></td>
        <td><%= link_to 'Show', problem_category %></td>
        <td><%= link_to 'Edit', edit_problem_category_path(problem_category) %></td>
        <td><%= link_to 'Destroy', problem_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Problem category', new_problem_category_path %>

app/views/problem_categories/new.html.erb
<h1>New problem_category</h1>

<%= render 'form' %>

<%= link_to 'Back', problem_categories_path %>

app/views/problem_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Problem:</strong>
  <%= @problem_category.problem_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @problem_category.category_id %>
</p>

<%= link_to 'Edit', edit_problem_category_path(@problem_category) %> |
<%= link_to 'Back', problem_categories_path %>