config/routes.rb
SecondTrial::Application.routes.draw do
    
  resources :problem_categories

  resources :categories

  resources :problem_in_contests

  resources :participants

  resources :contests

  resources :problems do
      resources :submissions
  end

    devise_for :users
    match 'users/:id' => 'users#show', :via => [:get]
    match '/about' => 'welcome#about', :via => [:get]
  get "welcome/index"
  

  root 'welcome#index'

  

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  belongs_to :user
  has_many :participants
  has_many :users, through: :participants
  has_many :problem_in_contests
  has_many :problem, through: :problem_in_contests
  validates :contestName, presence: true, uniqueness: {scope: :startDateTime, message: "Another contest of same name exists"}
  validates :startDateTime, presence: true
  validates :endDateTime, presence: true
  validate :startDateTime_cannot_be_in_past, :endDateTime_cannot_be_less_than_startDateTime

  def startDateTime_cannot_be_in_past
  	if(startDateTime<DateTime.now)
  		errors.add(:startDateTime, "can't be in the past")
  	end
  end

  def endDateTime_cannot_be_less_than_startDateTime
  		if(startDateTime>endDateTime)
  			errors.add(:endDateTime,"can't be less than start date time")
  		end
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.where('id!=?', 1).order(startDateTime: :desc)
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
    @problem_in_contest = ProblemInContest.new
    @problems = Problem.joins(:problem_in_contests).where('contest_id= ?',params[:id])
    @participants = Participant.where('contest_id=?',params[:id])
    @parorder=Submission.joins('INNER JOIN participants on submissions.user_id=participants.user_id AND submissions.contest_id=participants.contest_id  ').select("submissions.user_id, COUNT(distinct problem_id) as Solved,SUM(dateTimeOfSubmission) as TimeTaken").where('submissions.contest_id=? AND status="1"', params[:id]).group("submissions.user_id").order("COUNT(DISTINCT problem_id) desc, SUM(dateTimeOfSubmission) asc")
    @participant=Participant.new
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
  @contest = Contest.new(contest_params)
  civildate = "#{params[:contest]["startDateTime(1i)"].to_s}-#{params[:contest]["startDateTime(2i)"].to_s}-#{params[:contest]["startDateTime(3i)"].to_s} #{params[:contest]["startDateTime(4i)"].to_s}:#{params[:contest]["startDateTime(5i)"].to_s}"
  @contest.startDateTime= civildate
  civildate = "#{params[:contest]["endDateTime(1i)"].to_s}-#{params[:contest]["endDateTime(2i)"].to_s}-#{params[:contest]["endDateTime(3i)"].to_s} #{params[:contest]["endDateTime(4i)"].to_s}:#{params[:contest]["endDateTime(5i)"].to_s}"
  @contest.endDateTime = civildate


    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contest }
      else
        format.html { render action: 'new' }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:contestName, :startDateTime, :endDateTime, :contestStatus, :user_id)
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= simple_form_for(@contest) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :contestName, label: 'Contest Name' %>
    <%= f.input :startDateTime, label: 'Start Date and Time', start_year: Time.now.year-20, end_year: Time.now.year+5 %>
    <%= f.input :endDateTime, label: 'End Date and Time', start_year: Time.now.year-20, end_year: Time.now.year+5 %>
    <%= f.association :user, :as=>:hidden,:input_html=> { :value => current_user.id} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
 

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<h1>Listing Contests</h1>
<div class="table-responsive">
    
<table id="problems" class="table table-stripped">  
 <thead>
    <tr>
      <th>Contest name</th>
      <th>Start</th>
      <th>End</th>
      <th>Organiser</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= link_to(contest.contestName, contest) %></td>
        <td><%= contest.startDateTime %></td>
        <td><%= contest.endDateTime %></td>
        <td><%= contest.user.username %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if current_user.try(:admin?) %>
    <%= link_to 'New Contest', new_contest_path %>
<%end%>

app/views/contests/new.html.erb
<h1>New contest</h1>

<%= render 'form' %>

app/views/contests/show.html.erb
<% if @contest.id!=1 %>
<div class="container-fluid">
  <div  class="row">
  <p>
    <strong>Contest Name:</strong>
    <%= @contest.contestName %>
  </p>

  <p>
    <strong>Start:</strong>
    <%= @contest.startDateTime %>
  </p>

  <p>
    <strong>End:</strong>
    <%= @contest.endDateTime %>
  </p>

  <p>
    <strong>Hosted by:</strong>
    <%= @contest.user.username %>
  </p>
</div>
<%end%>

<%if current_user.try(:admin?)%>

<div class="row">
  <%= render 'shared/problemadd' %>
</div>
<%end%>

<%if @contest.startDateTime<DateTime.now or current_user.try(:admin?)%>
<div class="row">
  <div class="col-md-6">
  <%= render 'shared/problemslist' %>
  </div>

  <div  class="col-md-6">
  <%= render 'shared/scoreboard' %>
  </div>

</div>
<%end%>
<%if current_user.try(:admin?)%>
  <%= link_to 'Edit', edit_contest_path(@contest) %> |
  <%= link_to 'Create New Problem', new_problem_path %> 
<%end%>

<%if @contest.endDateTime>DateTime.now %>
<%= render 'shared/participantadd' %>
<% end%>

</div>