config/routes.rb
SecondTrial::Application.routes.draw do
    
  resources :problem_categories

  resources :categories

  resources :problem_in_contests

  resources :participants

  resources :contests

  resources :problems do
      resources :submissions
  end

    devise_for :users
    match 'users/:id' => 'users#show', :via => [:get]
    match '/about' => 'welcome#about', :via => [:get]
  get "welcome/index"
  

  root 'welcome#index'

  

end

app/models/problem_in_contest.rb
class ProblemInContest < ActiveRecord::Base
  belongs_to :problem
  belongs_to :contest
  
  validates :problem_id, uniqueness: {scope: :contest_id, message:"Problem is already added to contest" }
end

app/controllers/problem_in_contests_controller.rb
class ProblemInContestsController < ApplicationController
  before_action :set_problem_in_contest, only: [:show, :edit, :update, :destroy]

  # GET /problem_in_contests
  # GET /problem_in_contests.json
  def index
    @problem_in_contests = ProblemInContest.all
  end

  # GET /problem_in_contests/1
  # GET /problem_in_contests/1.json
  def show
  end

  # GET /problem_in_contests/new
  def new
    @problem_in_contest = ProblemInContest.new
  end

  # GET /problem_in_contests/1/edit
  def edit
  end

  # POST /problem_in_contests
  # POST /problem_in_contests.json
  def create
    @problem_in_contest = ProblemInContest.new(problem_in_contest_params)

    respond_to do |format|
      if @problem_in_contest.save
        format.html { redirect_to Contest.find(@problem_in_contest.contest_id), notice: 'Problem in contest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @problem_in_contest }
      else
        format.html { redirect_to Contest.find(@problem_in_contest.contest_id), notice: 'Problem is already present in contest' }
        format.json { render json: @problem_in_contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problem_in_contests/1
  # PATCH/PUT /problem_in_contests/1.json
  def update
    respond_to do |format|
      if @problem_in_contest.update(problem_in_contest_params)
        format.html { redirect_to @problem_in_contest, notice: 'Problem in contest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @problem_in_contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problem_in_contests/1
  # DELETE /problem_in_contests/1.json
  def destroy
    @problem_in_contest.destroy
    respond_to do |format|
      format.html { redirect_to problem_in_contests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem_in_contest
      @problem_in_contest = ProblemInContest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_in_contest_params
      params.require(:problem_in_contest).permit(:problem_id, :contest_id)
    end
end

app/helpers/problem_in_contests_helper.rb
module ProblemInContestsHelper
end

app/views/problem_in_contests/_form.html.erb
<%= simple_form_for(@problem_in_contest) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.association :problem, label_method: :title , value_method: :id , include_blank: false %>
    <%= f.association :contest, label_method: :contestName , value_method: :id , include_blank: false %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/problem_in_contests/edit.html.erb
<h1>Editing problem_in_contest</h1>

<%= render 'form' %>

app/views/problem_in_contests/index.html.erb
<h1>Listing problem in contests</h1>

<table>
  <thead>
    <tr>
      <th>Problem</th>
      <th>Contest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @problem_in_contests.each do |problem_in_contest| %>
      <tr>
        <td><%= problem_in_contest.problem %></td>
        <td><%= problem_in_contest.contest %></td>
        <td><%= link_to 'Show', problem_in_contest %></td>
        <td><%= link_to 'Edit', edit_problem_in_contest_path(problem_in_contest) %></td>
        <td><%= link_to 'Destroy', problem_in_contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Problem in contest', new_problem_in_contest_path %>

app/views/problem_in_contests/new.html.erb
<h1>New problem in contest</h1>

<%= render 'form' %>

<%= link_to 'Back', problem_in_contests_path %>

app/views/problem_in_contests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Problem:</strong>
  <%= @problem_in_contest.problem %>
</p>

<p>
  <strong>Contest:</strong>
  <%= @problem_in_contest.contest %>
</p>

<%= link_to 'Edit', edit_problem_in_contest_path(@problem_in_contest) %> |
<%= link_to 'Back', problem_in_contests_path %>